{{- if and .Values.cull.enabled .Values.cull.maxAge }}
{{- if .Values.serviceAccounts.podCuller.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.podCuller.name }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.serviceAccounts.podCuller.name }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""      # "" indicates the core API group
  resources:
    - pods
  verbs:
    - delete
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.serviceAccounts.podCuller.name }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.serviceAccounts.podCuller.name }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccounts.podCuller.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
